/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as core from "../../../core";
import { PatchApi } from "../../..";

export interface Request {
  _token?: core.Supplier<core.BearerToken>;
  id: PatchApi.estimates.EstimateId;
}

export type Response = core.APIResponse<PatchApi.estimates.Estimate, PatchApi.estimates.retrieve.Error>;
export type Error = Error._Unknown;

export declare namespace Error {
  interface _Unknown extends _Utils {
    errorName: void;
    content: core.Fetcher.Error;
  }

  interface _Utils {
    _visit: <Result>(visitor: Error._Visitor<Result>) => Result;
  }

  interface _Visitor<Result> {
    _other: (value: core.Fetcher.Error) => Result;
  }
}
