/**
 * This file auto-generated by Fern from our API Definition.
 */

/**
 * The optional issued_to object lets you specify who the order is for. This information is what will appear on the certificate.
 */
export interface IssuedTo {
  /** The name of the issuee */
  name: string;
  /** The email address of the issuee */
  email: string;
}
