/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PatchApi } from "../../..";

/**
 * line_items represent how your order was split across different projects and vintage_years, and how much was spent for each.
 */
export interface LineItem {
  /** The identifier for this order line item */
  id: PatchApi.orders.ItemId;
  /** An object containing information about the project associated with the inventory allocated. */
  project: PatchApi.orders.Project;
  /** The year in which the climate impacts of the project occurred, or will occur. */
  vintageYear: number;
  /** The amount ordered for the given project and vintage year. */
  amount: number;
  /** The unit of measurement (ie "g" or "Wh") for the amount ordered for the given project and vintage year. */
  unit: string;
  /** The price for the given amount ordered for the given project and vintage year. Does not include any Patch fee. Prices are always represented in the smallest currency unit (ie cents for USD). */
  price: number;
  /** The currency code for the price. */
  currency: string;
}
