/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PatchApi } from "../../..";

export interface Order {
  /** A unique uid for the record. UIDs will be prepended by ord_prod or ord_test depending on the mode it was created in. */
  id: PatchApi.orders.OrderId;
  /** The timestamp at which the order was created */
  createdAt: string;
  /** A boolean indicating if this order is a production or demo mode order. */
  production: boolean;
  /** The current state of the order. */
  state: string;
  /** The amount in units purchased through this order. Minimum value: 0. Maximum value: 100,000,000,000. */
  amount: number;
  /** The unit of measurement (ie "g" or "Wh") for the amount ordered. */
  unit: string;
  /** The total price for the amount ordered. Prices are always represented in the smallest currency unit (ie cents for USD). */
  price: number;
  /** integer */
  patchFee: number;
  /** The currency code for the price and patch_fee. */
  currency?: string;
  /** The url of this order in the public registry. */
  registryUrl?: string;
  /** An optional JSON object containing metadata for this order. */
  metadata?: string;
  /** An array containing the line items allocated for this order. Line items are grouped by project, vintage year, and price. */
  lineItems: PatchApi.orders.LineItem[];
  /** An object containing the name & email of the party the inventory will be issued to. */
  issuedTo?: PatchApi.orders.IssuedTo;
}
