/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PatchApi } from "../../..";

export interface Project {
  /** The unique uid for a project. UIDs will be prepended by pro_prod or pro_test depending on the mode it was created in. */
  id: PatchApi.orders.ProjectId;
  /** The name of the project. */
  name: string;
}
