/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PatchApi } from "../../..";
import * as core from "../../../core";

export const id: core.schemas.Schema<id.Raw, PatchApi.commons.id> = core.schemas.string();

export declare namespace id {
  type Raw = string;
}
