/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PatchApi } from "../../..";
import * as core from "../../../core";

export const ProjectId: core.schemas.Schema<ProjectId.Raw, PatchApi.orders.ProjectId> = core.schemas.string();

export declare namespace ProjectId {
  type Raw = string;
}
