/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import { PatchApi } from "../../..";
import * as core from "../../../core";

export const Response: core.schemas.Schema<serializers.estimates.Estimate.Raw[], PatchApi.estimates.Estimate[]> =
  core.schemas.list(core.schemas.lazyObject(() => serializers.estimates.Estimate));
