/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PatchApi } from "../../..";

/**
 * You must supply either distance_m or both origin_airport and destination_airport.
 */
export interface CreateFlightEstimateRequest {
  /** The flight travel distance in meters. Uses orign and destination airports to compute distance */
  distanceM?: number;
  /** The IATA code of the origin airport. Uses distance_m */
  originAirport?: string;
  /** The IATA code of the destination airport. Uses distance_m */
  destinationAirport?: string;
  /** The IATA code of the aircraft. Defaults to EPA average emission factor */
  aircraftCode?: string;
  /** Defaults to economy */
  cabinClass?: PatchApi.estimates.CabinClass;
  /** The number of passengers in your party. Defaults to 1. */
  passengerCount?: number;
  /** Only selects offsets from the specified project. Selects offsets from any project */
  projectId?: string;
  /** If true, creates a draft order. If false or empty, creates only the estimate */
  createOrder?: boolean;
}
