/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PatchApi } from "../../..";
import * as core from "../../../core";

export const CabinClass: core.schemas.Schema<CabinClass.Raw, PatchApi.estimates.CabinClass> = core.schemas
  .string()
  .transform<PatchApi.estimates.CabinClass>({
    parse: (value) => {
      switch (value) {
        case "economy": {
          return PatchApi.estimates.CabinClass.Economy;
        }
        case "business": {
          return PatchApi.estimates.CabinClass.Business;
        }
        case "first": {
          return PatchApi.estimates.CabinClass.First;
        }
        default: {
          return {
            value: value,
            visit: (visitor) => visitor._other(value),
          };
        }
      }
    },
    json: (value) => value.value,
  });

export declare namespace CabinClass {
  type Raw = string;
}
