/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PatchApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const Estimate: core.schemas.ObjectSchema<Estimate.Raw, PatchApi.estimates.Estimate> = core.schemas.object({
  id: core.schemas.lazy(() => schemas.estimates.EstimateId),
  production: core.schemas.boolean(),
  type: core.schemas.string(),
  massG: core.schemas.property("mass_g", core.schemas.number()),
  order: core.schemas.lazyObject(() => schemas.orders.Order).optional(),
});

export declare namespace Estimate {
  interface Raw {
    id: schemas.estimates.EstimateId.Raw;
    production: boolean;
    type: string;
    mass_g: number;
    order?: schemas.orders.Order.Raw | null;
  }
}
