/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PatchApi } from "../../..";
import * as core from "../../../core";

export const IssuedTo: core.schemas.ObjectSchema<IssuedTo.Raw, PatchApi.orders.IssuedTo> = core.schemas.object({
  name: core.schemas.string(),
  email: core.schemas.string(),
});

export declare namespace IssuedTo {
  interface Raw {
    name: string;
    email: string;
  }
}
