/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PatchApi } from "../../..";
import * as core from "../../../core";

export const ItemId: core.schemas.Schema<ItemId.Raw, PatchApi.orders.ItemId> = core.schemas.string();

export declare namespace ItemId {
  type Raw = string;
}
