/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PatchApi } from "../../..";
import * as core from "../../../core";

export const OrderId: core.schemas.Schema<OrderId.Raw, PatchApi.orders.OrderId> = core.schemas.string();

export declare namespace OrderId {
  type Raw = string;
}
