/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PatchApi } from "../../..";
import * as core from "../../../core";
import * as schemas from "../..";

export const Project: core.schemas.ObjectSchema<Project.Raw, PatchApi.orders.Project> = core.schemas.object({
  id: core.schemas.lazy(() => schemas.orders.ProjectId),
  name: core.schemas.string(),
});

export declare namespace Project {
  interface Raw {
    id: schemas.orders.ProjectId.Raw;
    name: string;
  }
}
