/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as core from "./core";
import { Client as EstimatesClient } from "./resources/estimates/client/Client";

export declare namespace PatchApiClient {
  interface Options {
    environment: string;
    auth?: {
      token?: core.Supplier<core.BearerToken>;
    };
  }
}

export class PatchApiClient {
  constructor(private readonly options: PatchApiClient.Options) {}

  #estimates: EstimatesClient | undefined;

  public get estimates(): EstimatesClient {
    return (this.#estimates ??= new EstimatesClient(this.options));
  }
}
