/**
 * This file auto-generated by Fern from our API Definition.
 */

import { PatchApi } from "../../..";
import * as core from "../../../core";

export const EstimateId: core.schemas.Schema<EstimateId.Raw, PatchApi.estimates.EstimateId> = core.schemas.string();

export declare namespace EstimateId {
  type Raw = string;
}
