/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as core from "../core";
import { Client as EstimatesServiceClient } from "./estimates/client/Client";

export namespace Client {
  export interface Options {
    _origin: string;
    _token?: core.Supplier<core.BearerToken>;
  }
}

export class Client {
  constructor(private readonly options: Client.Options) {}

  #estimates: EstimatesServiceClient | undefined;

  public get estimates(): EstimatesServiceClient {
    return (this.#estimates ??= new EstimatesServiceClient({
      _origin: this.options._origin,
      _token: this.options._token,
    }));
  }
}
