/**
 * This file auto-generated by Fern from our API Definition.
 */

import * as schemas from "../..";
import { PatchApi } from "../../..";
import * as core from "../../../core";

export const Response: core.schemas.Schema<schemas.estimates.Estimate.Raw[], PatchApi.estimates.Estimate[]> =
  core.schemas.list(core.schemas.lazyObject(() => schemas.estimates.Estimate));
